version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on: [db]

  app:
    build: .
    ports:
      - 8000:8000
    depends_on: [db]